ci: use faulty cluster name to restart ps1 and router1 and check cluster health status

diff --git a/.github/workflows/CI_cluster.yml b/.github/workflows/CI_cluster.yml
--- a/.github/workflows/CI_cluster.yml
+++ b/.github/workflows/CI_cluster.yml
@@ -149,12 +149,29 @@ jobs:
 
     - name: Run tests for fail server
       run: |
-        set -e
         cd test
         pytest test_cluster_ps.py -x -k "TestFailServerPrepare" --log-cli-level=INFO
-        cd .. && docker-compose -f cloud/docker-compose.yml stop ps1
+        sed -i 's/name = "vearch"/name = "test"/' ../cloud/config_cluster.toml
+        cd .. && docker-compose -f cloud/docker-compose.yml restart ps1
+        docker-compose -f cloud/docker-compose.yml restart router1
+        sed -i 's/name = "test"/name = "vearch"/' cloud/config_cluster.toml
         sleep 60
+        status=$(curl -u root:secret http://127.0.0.1:8817/cluster/health | jq -r '.data[0].spaces[0].status')
+        if [ "$status" != "yellow" ]; then
+          echo "Error: Status is not yellow. Status is $status."
+          exit 1
+        else
+          echo "Status is yellow."
+        fi
+        router_status=$(curl -u root:secret http://172.16.238.14:9001 || true)
+        if [ $? != 7 ]; then
+          echo "Router status is not OK. Status is $router_status."
+        else
+          echo "Router is OK. Status is $router_status."
+          exit 1
+        fi
         docker-compose -f cloud/docker-compose.yml up ps4 -d
+        docker-compose -f cloud/docker-compose.yml restart router1
         sleep 60
         status=$(curl -u root:secret http://127.0.0.1:8817/cluster/health | jq -r '.data[0].spaces[0].status')
         if [ "$status" != "green" ]; then
